/* dfitpack-f2pywrappers.f -- translated by f2c (version 20190311).
   You must link the resulting object file with libf2c:
	on Microsoft Windows system, link with libf2c.lib;
	on Linux or Unix systems, link with .../path/to/libf2c.a -lm
	or, if you install libf2c.a in a standard place, with -lf2c -lm
	-- in that order, at the end of the command line, as in
		cc *.o -lf2c -lm
	Source for libf2c is in /netlib/f2c/libf2c.zip, e.g.,

		http://www.netlib.org/f2c/libf2c.zip
*/

#include "f2c.h"

/*     -*- fortran -*- */
/*     This file is autogenerated with f2py (version:2) */
/*     It contains Fortran 77 wrappers to fortran functions. */
/* Subroutine */ int f2pywrapsplint_(doublereal *splintf2pywrap, doublereal *
	t, integer *n, doublereal *c__, integer *k, doublereal *a, doublereal 
	*b, doublereal *wrk)
{
    extern doublereal splint_(doublereal *, integer *, doublereal *, integer *
	    , doublereal *, doublereal *, doublereal *);

    /* Parameter adjustments */
    --wrk;
    --c__;
    --t;

    /* Function Body */
    *splintf2pywrap = splint_(&t[1], n, &c__[1], k, a, b, &wrk[1]);
    return 0;
} /* f2pywrapsplint_ */

/* Subroutine */ int f2pywrapdblint_(doublereal *dblintf2pywrap, doublereal *
	tx, integer *nx, doublereal *ty, integer *ny, doublereal *c__, 
	integer *kx, integer *ky, doublereal *xb, doublereal *xe, doublereal *
	yb, doublereal *ye, doublereal *wrk)
{
    extern doublereal dblint_(doublereal *, integer *, doublereal *, integer *
	    , doublereal *, integer *, integer *, doublereal *, doublereal *, 
	    doublereal *, doublereal *, doublereal *);

    /* Parameter adjustments */
    --tx;
    --ty;
    --wrk;
    --c__;

    /* Function Body */
    *dblintf2pywrap = dblint_(&tx[1], nx, &ty[1], ny, &c__[1], kx, ky, xb, xe,
	     yb, ye, &wrk[1]);
    return 0;
} /* f2pywrapdblint_ */

