/* _fblas-f2pywrappers.f -- translated by f2c (version 20190311).
   You must link the resulting object file with libf2c:
	on Microsoft Windows system, link with libf2c.lib;
	on Linux or Unix systems, link with .../path/to/libf2c.a -lm
	or, if you install libf2c.a in a standard place, with -lf2c -lm
	-- in that order, at the end of the command line, as in
		cc *.o -lf2c -lm
	Source for libf2c is in /netlib/f2c/libf2c.zip, e.g.,

		http://www.netlib.org/f2c/libf2c.zip
*/

#include "f2c.h"

/*     -*- fortran -*- */
/*     This file is autogenerated with f2py (version:2) */
/*     It contains Fortran 77 wrappers to fortran functions. */
/* Subroutine */ int f2pywrapsdot_(real *sdotf2pywrap, integer *n, real *x, 
	integer *offx, integer *incx, real *y, integer *offy, integer *incy)
{
    extern doublereal sdot_(integer *, real *, integer *, integer *, real *, 
	    integer *, integer *);

    /* Parameter adjustments */
    --y;
    --x;

    /* Function Body */
    *sdotf2pywrap = sdot_(n, &x[1], offx, incx, &y[1], offy, incy);
    return 0;
} /* f2pywrapsdot_ */

/* Subroutine */ int f2pywrapddot_(doublereal *ddotf2pywrap, integer *n, 
	doublereal *x, integer *offx, integer *incx, doublereal *y, integer *
	offy, integer *incy)
{
    extern doublereal ddot_(integer *, doublereal *, integer *, integer *, 
	    doublereal *, integer *, integer *);

    /* Parameter adjustments */
    --y;
    --x;

    /* Function Body */
    *ddotf2pywrap = ddot_(n, &x[1], offx, incx, &y[1], offy, incy);
    return 0;
} /* f2pywrapddot_ */

/* Subroutine */ int f2pywrapcdotu_(complex *cdotuf2pywrap, integer *n, 
	complex *x, integer *offx, integer *incx, complex *y, integer *offy, 
	integer *incy)
{
    /* System generated locals */
    complex q__1;

    /* Local variables */
    extern /* Complex */ VOID wcdotu_(complex *, integer *, complex *, 
	    integer *, integer *, complex *, integer *, integer *);

    /* Parameter adjustments */
    --y;
    --x;

    /* Function Body */
    wcdotu_(&q__1, n, &x[1], offx, incx, &y[1], offy, incy);
    cdotuf2pywrap->r = q__1.r, cdotuf2pywrap->i = q__1.i;
    return 0;
} /* f2pywrapcdotu_ */

/* Subroutine */ int f2pywrapzdotu_(doublecomplex *zdotuf2pywrap, integer *n, 
	doublecomplex *x, integer *offx, integer *incx, doublecomplex *y, 
	integer *offy, integer *incy)
{
    /* System generated locals */
    doublecomplex z__1;

    /* Local variables */
    extern /* Double Complex */ VOID wzdotu_(doublecomplex *, integer *, 
	    doublecomplex *, integer *, integer *, doublecomplex *, integer *,
	     integer *);

    /* Parameter adjustments */
    --y;
    --x;

    /* Function Body */
    wzdotu_(&z__1, n, &x[1], offx, incx, &y[1], offy, incy);
    zdotuf2pywrap->r = z__1.r, zdotuf2pywrap->i = z__1.i;
    return 0;
} /* f2pywrapzdotu_ */

/* Subroutine */ int f2pywrapcdotc_(complex *cdotcf2pywrap, integer *n, 
	complex *x, integer *offx, integer *incx, complex *y, integer *offy, 
	integer *incy)
{
    /* System generated locals */
    complex q__1;

    /* Local variables */
    extern /* Complex */ VOID wcdotc_(complex *, integer *, complex *, 
	    integer *, integer *, complex *, integer *, integer *);

    /* Parameter adjustments */
    --y;
    --x;

    /* Function Body */
    wcdotc_(&q__1, n, &x[1], offx, incx, &y[1], offy, incy);
    cdotcf2pywrap->r = q__1.r, cdotcf2pywrap->i = q__1.i;
    return 0;
} /* f2pywrapcdotc_ */

/* Subroutine */ int f2pywrapzdotc_(doublecomplex *zdotcf2pywrap, integer *n, 
	doublecomplex *x, integer *offx, integer *incx, doublecomplex *y, 
	integer *offy, integer *incy)
{
    /* System generated locals */
    doublecomplex z__1;

    /* Local variables */
    extern /* Double Complex */ VOID wzdotc_(doublecomplex *, integer *, 
	    doublecomplex *, integer *, integer *, doublecomplex *, integer *,
	     integer *);

    /* Parameter adjustments */
    --y;
    --x;

    /* Function Body */
    wzdotc_(&z__1, n, &x[1], offx, incx, &y[1], offy, incy);
    zdotcf2pywrap->r = z__1.r, zdotcf2pywrap->i = z__1.i;
    return 0;
} /* f2pywrapzdotc_ */

/* Subroutine */ int f2pywrapsnrm2_(real *snrm2f2pywrap, integer *n, real *x, 
	integer *offx, integer *incx)
{
    extern doublereal snrm2_(integer *, real *, integer *, integer *);

    /* Parameter adjustments */
    --x;

    /* Function Body */
    *snrm2f2pywrap = snrm2_(n, &x[1], offx, incx);
    return 0;
} /* f2pywrapsnrm2_ */

/* Subroutine */ int f2pywrapscnrm2_(real *scnrm2f2pywrap, integer *n, 
	complex *x, integer *offx, integer *incx)
{
    extern doublereal scnrm2_(integer *, complex *, integer *, integer *);

    /* Parameter adjustments */
    --x;

    /* Function Body */
    *scnrm2f2pywrap = scnrm2_(n, &x[1], offx, incx);
    return 0;
} /* f2pywrapscnrm2_ */

/* Subroutine */ int f2pywrapdnrm2_(doublereal *dnrm2f2pywrap, integer *n, 
	doublereal *x, integer *offx, integer *incx)
{
    extern doublereal dnrm2_(integer *, doublereal *, integer *, integer *);

    /* Parameter adjustments */
    --x;

    /* Function Body */
    *dnrm2f2pywrap = dnrm2_(n, &x[1], offx, incx);
    return 0;
} /* f2pywrapdnrm2_ */

/* Subroutine */ int f2pywrapdznrm2_(doublereal *dznrm2f2pywrap, integer *n, 
	doublecomplex *x, integer *offx, integer *incx)
{
    extern doublereal dznrm2_(integer *, doublecomplex *, integer *, integer *
	    );

    /* Parameter adjustments */
    --x;

    /* Function Body */
    *dznrm2f2pywrap = dznrm2_(n, &x[1], offx, incx);
    return 0;
} /* f2pywrapdznrm2_ */

/* Subroutine */ int f2pywrapsasum_(real *sasumf2pywrap, integer *n, real *x, 
	integer *offx, integer *incx)
{
    extern doublereal sasum_(integer *, real *, integer *, integer *);

    /* Parameter adjustments */
    --x;

    /* Function Body */
    *sasumf2pywrap = sasum_(n, &x[1], offx, incx);
    return 0;
} /* f2pywrapsasum_ */

/* Subroutine */ int f2pywrapscasum_(real *scasumf2pywrap, integer *n, 
	complex *x, integer *offx, integer *incx)
{
    extern doublereal scasum_(integer *, complex *, integer *, integer *);

    /* Parameter adjustments */
    --x;

    /* Function Body */
    *scasumf2pywrap = scasum_(n, &x[1], offx, incx);
    return 0;
} /* f2pywrapscasum_ */

/* Subroutine */ int f2pywrapdasum_(doublereal *dasumf2pywrap, integer *n, 
	doublereal *x, integer *offx, integer *incx)
{
    extern doublereal dasum_(integer *, doublereal *, integer *, integer *);

    /* Parameter adjustments */
    --x;

    /* Function Body */
    *dasumf2pywrap = dasum_(n, &x[1], offx, incx);
    return 0;
} /* f2pywrapdasum_ */

/* Subroutine */ int f2pywrapdzasum_(doublereal *dzasumf2pywrap, integer *n, 
	doublecomplex *x, integer *offx, integer *incx)
{
    extern doublereal dzasum_(integer *, doublecomplex *, integer *, integer *
	    );

    /* Parameter adjustments */
    --x;

    /* Function Body */
    *dzasumf2pywrap = dzasum_(n, &x[1], offx, incx);
    return 0;
} /* f2pywrapdzasum_ */

