/* _lapack_subroutine_wrappers.f -- translated by f2c (version 20190311).
   You must link the resulting object file with libf2c:
	on Microsoft Windows system, link with libf2c.lib;
	on Linux or Unix systems, link with .../path/to/libf2c.a -lm
	or, if you install libf2c.a in a standard place, with -lf2c -lm
	-- in that order, at the end of the command line, as in
		cc *.o -lf2c -lm
	Source for libf2c is in /netlib/f2c/libf2c.zip, e.g.,

		http://www.netlib.org/f2c/libf2c.zip
*/

#include "f2c.h"

/*     This file was generated by _generate_pyx.py. */
/*     Do not edit this file directly. */
/* Subroutine */ int chla_transtypewrp__(char *ret, integer *trans, ftnlen 
	ret_len)
{
    /* System generated locals */
    char ch__1[1];

    /* Local variables */
    extern /* Character */ VOID chla_transtype__(char *, ftnlen, integer *);

    chla_transtype__(ch__1, (ftnlen)1, trans);
    *(unsigned char *)ret = *(unsigned char *)&ch__1[0];
    return 0;
} /* chla_transtypewrp__ */

/* Subroutine */ int cladivwrp_(complex *ret, complex *x, complex *y)
{
    /* System generated locals */
    complex q__1;

    /* Local variables */
    extern /* Complex */ VOID wcladiv_(complex *, complex *, complex *);

    wcladiv_(&q__1, x, y);
    ret->r = q__1.r, ret->i = q__1.i;
    return 0;
} /* cladivwrp_ */

/* Subroutine */ int clangbwrp_(real *ret, char *norm, integer *n, integer *
	kl, integer *ku, complex *ab, integer *ldab, real *work, ftnlen 
	norm_len)
{
    extern doublereal clangb_(char *, integer *, integer *, integer *, 
	    complex *, integer *, real *, ftnlen);

    *ret = clangb_(norm, n, kl, ku, ab, ldab, work, (ftnlen)1);
    return 0;
} /* clangbwrp_ */

/* Subroutine */ int clangewrp_(real *ret, char *norm, integer *m, integer *n,
	 complex *a, integer *lda, real *work, ftnlen norm_len)
{
    extern doublereal clange_(char *, integer *, integer *, complex *, 
	    integer *, real *, ftnlen);

    *ret = clange_(norm, m, n, a, lda, work, (ftnlen)1);
    return 0;
} /* clangewrp_ */

/* Subroutine */ int clangtwrp_(real *ret, char *norm, integer *n, complex *
	dl, complex *d__, complex *du, ftnlen norm_len)
{
    extern doublereal clangt_(char *, integer *, complex *, complex *, 
	    complex *, ftnlen);

    *ret = clangt_(norm, n, dl, d__, du, (ftnlen)1);
    return 0;
} /* clangtwrp_ */

/* Subroutine */ int clanhbwrp_(real *ret, char *norm, char *uplo, integer *n,
	 integer *k, complex *ab, integer *ldab, real *work, ftnlen norm_len, 
	ftnlen uplo_len)
{
    extern doublereal clanhb_(char *, char *, integer *, integer *, complex *,
	     integer *, real *, ftnlen, ftnlen);

    *ret = clanhb_(norm, uplo, n, k, ab, ldab, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* clanhbwrp_ */

/* Subroutine */ int clanhewrp_(real *ret, char *norm, char *uplo, integer *n,
	 complex *a, integer *lda, real *work, ftnlen norm_len, ftnlen 
	uplo_len)
{
    extern doublereal clanhe_(char *, char *, integer *, complex *, integer *,
	     real *, ftnlen, ftnlen);

    *ret = clanhe_(norm, uplo, n, a, lda, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* clanhewrp_ */

/* Subroutine */ int clanhfwrp_(real *ret, char *norm, char *transr, char *
	uplo, integer *n, complex *a, real *work, ftnlen norm_len, ftnlen 
	transr_len, ftnlen uplo_len)
{
    extern doublereal clanhf_(char *, char *, char *, integer *, complex *, 
	    real *, ftnlen, ftnlen, ftnlen);

    /* Parameter adjustments */
    --a;

    /* Function Body */
    *ret = clanhf_(norm, transr, uplo, n, &a[1], work, (ftnlen)1, (ftnlen)1, (
	    ftnlen)1);
    return 0;
} /* clanhfwrp_ */

/* Subroutine */ int clanhpwrp_(real *ret, char *norm, char *uplo, integer *n,
	 complex *ap, real *work, ftnlen norm_len, ftnlen uplo_len)
{
    extern doublereal clanhp_(char *, char *, integer *, complex *, real *, 
	    ftnlen, ftnlen);

    *ret = clanhp_(norm, uplo, n, ap, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* clanhpwrp_ */

/* Subroutine */ int clanhswrp_(real *ret, char *norm, integer *n, complex *a,
	 integer *lda, real *work, ftnlen norm_len)
{
    extern doublereal clanhs_(char *, integer *, complex *, integer *, real *,
	     ftnlen);

    *ret = clanhs_(norm, n, a, lda, work, (ftnlen)1);
    return 0;
} /* clanhswrp_ */

/* Subroutine */ int clanhtwrp_(real *ret, char *norm, integer *n, real *d__, 
	complex *e, ftnlen norm_len)
{
    extern doublereal clanht_(char *, integer *, real *, complex *, ftnlen);

    *ret = clanht_(norm, n, d__, e, (ftnlen)1);
    return 0;
} /* clanhtwrp_ */

/* Subroutine */ int clansbwrp_(real *ret, char *norm, char *uplo, integer *n,
	 integer *k, complex *ab, integer *ldab, real *work, ftnlen norm_len, 
	ftnlen uplo_len)
{
    extern doublereal clansb_(char *, char *, integer *, integer *, complex *,
	     integer *, real *, ftnlen, ftnlen);

    *ret = clansb_(norm, uplo, n, k, ab, ldab, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* clansbwrp_ */

/* Subroutine */ int clanspwrp_(real *ret, char *norm, char *uplo, integer *n,
	 complex *ap, real *work, ftnlen norm_len, ftnlen uplo_len)
{
    extern doublereal clansp_(char *, char *, integer *, complex *, real *, 
	    ftnlen, ftnlen);

    *ret = clansp_(norm, uplo, n, ap, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* clanspwrp_ */

/* Subroutine */ int clansywrp_(real *ret, char *norm, char *uplo, integer *n,
	 complex *a, integer *lda, real *work, ftnlen norm_len, ftnlen 
	uplo_len)
{
    extern doublereal clansy_(char *, char *, integer *, complex *, integer *,
	     real *, ftnlen, ftnlen);

    *ret = clansy_(norm, uplo, n, a, lda, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* clansywrp_ */

/* Subroutine */ int clantbwrp_(real *ret, char *norm, char *uplo, char *diag,
	 integer *n, integer *k, complex *ab, integer *ldab, real *work, 
	ftnlen norm_len, ftnlen uplo_len, ftnlen diag_len)
{
    extern doublereal clantb_(char *, char *, char *, integer *, integer *, 
	    complex *, integer *, real *, ftnlen, ftnlen, ftnlen);

    *ret = clantb_(norm, uplo, diag, n, k, ab, ldab, work, (ftnlen)1, (ftnlen)
	    1, (ftnlen)1);
    return 0;
} /* clantbwrp_ */

/* Subroutine */ int clantpwrp_(real *ret, char *norm, char *uplo, char *diag,
	 integer *n, complex *ap, real *work, ftnlen norm_len, ftnlen 
	uplo_len, ftnlen diag_len)
{
    extern doublereal clantp_(char *, char *, char *, integer *, complex *, 
	    real *, ftnlen, ftnlen, ftnlen);

    *ret = clantp_(norm, uplo, diag, n, ap, work, (ftnlen)1, (ftnlen)1, (
	    ftnlen)1);
    return 0;
} /* clantpwrp_ */

/* Subroutine */ int clantrwrp_(real *ret, char *norm, char *uplo, char *diag,
	 integer *m, integer *n, complex *a, integer *lda, real *work, ftnlen 
	norm_len, ftnlen uplo_len, ftnlen diag_len)
{
    extern doublereal clantr_(char *, char *, char *, integer *, integer *, 
	    complex *, integer *, real *, ftnlen, ftnlen, ftnlen);

    *ret = clantr_(norm, uplo, diag, m, n, a, lda, work, (ftnlen)1, (ftnlen)1,
	     (ftnlen)1);
    return 0;
} /* clantrwrp_ */

/* Subroutine */ int disnanwrp_(logical *ret, doublereal *din)
{
    extern logical disnan_(doublereal *);

    *ret = disnan_(din);
    return 0;
} /* disnanwrp_ */

/* Subroutine */ int dlamchwrp_(doublereal *ret, char *cmach, ftnlen 
	cmach_len)
{
    extern doublereal dlamch_(char *, ftnlen);

    *ret = dlamch_(cmach, (ftnlen)1);
    return 0;
} /* dlamchwrp_ */

/* Subroutine */ int dlanegwrp_(integer *ret, integer *n, doublereal *d__, 
	doublereal *lld, doublereal *sigma, doublereal *pivmin, integer *r__)
{
    extern integer dlaneg_(integer *, doublereal *, doublereal *, doublereal *
	    , doublereal *, integer *);

    *ret = dlaneg_(n, d__, lld, sigma, pivmin, r__);
    return 0;
} /* dlanegwrp_ */

/* Subroutine */ int dlangbwrp_(doublereal *ret, char *norm, integer *n, 
	integer *kl, integer *ku, doublereal *ab, integer *ldab, doublereal *
	work, ftnlen norm_len)
{
    extern doublereal dlangb_(char *, integer *, integer *, integer *, 
	    doublereal *, integer *, doublereal *, ftnlen);

    *ret = dlangb_(norm, n, kl, ku, ab, ldab, work, (ftnlen)1);
    return 0;
} /* dlangbwrp_ */

/* Subroutine */ int dlangewrp_(doublereal *ret, char *norm, integer *m, 
	integer *n, doublereal *a, integer *lda, doublereal *work, ftnlen 
	norm_len)
{
    extern doublereal dlange_(char *, integer *, integer *, doublereal *, 
	    integer *, doublereal *, ftnlen);

    *ret = dlange_(norm, m, n, a, lda, work, (ftnlen)1);
    return 0;
} /* dlangewrp_ */

/* Subroutine */ int dlangtwrp_(doublereal *ret, char *norm, integer *n, 
	doublereal *dl, doublereal *d__, doublereal *du, ftnlen norm_len)
{
    extern doublereal dlangt_(char *, integer *, doublereal *, doublereal *, 
	    doublereal *, ftnlen);

    *ret = dlangt_(norm, n, dl, d__, du, (ftnlen)1);
    return 0;
} /* dlangtwrp_ */

/* Subroutine */ int dlanhswrp_(doublereal *ret, char *norm, integer *n, 
	doublereal *a, integer *lda, doublereal *work, ftnlen norm_len)
{
    extern doublereal dlanhs_(char *, integer *, doublereal *, integer *, 
	    doublereal *, ftnlen);

    *ret = dlanhs_(norm, n, a, lda, work, (ftnlen)1);
    return 0;
} /* dlanhswrp_ */

/* Subroutine */ int dlansbwrp_(doublereal *ret, char *norm, char *uplo, 
	integer *n, integer *k, doublereal *ab, integer *ldab, doublereal *
	work, ftnlen norm_len, ftnlen uplo_len)
{
    extern doublereal dlansb_(char *, char *, integer *, integer *, 
	    doublereal *, integer *, doublereal *, ftnlen, ftnlen);

    *ret = dlansb_(norm, uplo, n, k, ab, ldab, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* dlansbwrp_ */

/* Subroutine */ int dlansfwrp_(doublereal *ret, char *norm, char *transr, 
	char *uplo, integer *n, doublereal *a, doublereal *work, ftnlen 
	norm_len, ftnlen transr_len, ftnlen uplo_len)
{
    extern doublereal dlansf_(char *, char *, char *, integer *, doublereal *,
	     doublereal *, ftnlen, ftnlen, ftnlen);

    /* Parameter adjustments */
    --a;

    /* Function Body */
    *ret = dlansf_(norm, transr, uplo, n, &a[1], work, (ftnlen)1, (ftnlen)1, (
	    ftnlen)1);
    return 0;
} /* dlansfwrp_ */

/* Subroutine */ int dlanspwrp_(doublereal *ret, char *norm, char *uplo, 
	integer *n, doublereal *ap, doublereal *work, ftnlen norm_len, ftnlen 
	uplo_len)
{
    extern doublereal dlansp_(char *, char *, integer *, doublereal *, 
	    doublereal *, ftnlen, ftnlen);

    *ret = dlansp_(norm, uplo, n, ap, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* dlanspwrp_ */

/* Subroutine */ int dlanstwrp_(doublereal *ret, char *norm, integer *n, 
	doublereal *d__, doublereal *e, ftnlen norm_len)
{
    extern doublereal dlanst_(char *, integer *, doublereal *, doublereal *, 
	    ftnlen);

    *ret = dlanst_(norm, n, d__, e, (ftnlen)1);
    return 0;
} /* dlanstwrp_ */

/* Subroutine */ int dlansywrp_(doublereal *ret, char *norm, char *uplo, 
	integer *n, doublereal *a, integer *lda, doublereal *work, ftnlen 
	norm_len, ftnlen uplo_len)
{
    extern doublereal dlansy_(char *, char *, integer *, doublereal *, 
	    integer *, doublereal *, ftnlen, ftnlen);

    *ret = dlansy_(norm, uplo, n, a, lda, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* dlansywrp_ */

/* Subroutine */ int dlantbwrp_(doublereal *ret, char *norm, char *uplo, char 
	*diag, integer *n, integer *k, doublereal *ab, integer *ldab, 
	doublereal *work, ftnlen norm_len, ftnlen uplo_len, ftnlen diag_len)
{
    extern doublereal dlantb_(char *, char *, char *, integer *, integer *, 
	    doublereal *, integer *, doublereal *, ftnlen, ftnlen, ftnlen);

    *ret = dlantb_(norm, uplo, diag, n, k, ab, ldab, work, (ftnlen)1, (ftnlen)
	    1, (ftnlen)1);
    return 0;
} /* dlantbwrp_ */

/* Subroutine */ int dlantpwrp_(doublereal *ret, char *norm, char *uplo, char 
	*diag, integer *n, doublereal *ap, doublereal *work, ftnlen norm_len, 
	ftnlen uplo_len, ftnlen diag_len)
{
    extern doublereal dlantp_(char *, char *, char *, integer *, doublereal *,
	     doublereal *, ftnlen, ftnlen, ftnlen);

    *ret = dlantp_(norm, uplo, diag, n, ap, work, (ftnlen)1, (ftnlen)1, (
	    ftnlen)1);
    return 0;
} /* dlantpwrp_ */

/* Subroutine */ int dlantrwrp_(doublereal *ret, char *norm, char *uplo, char 
	*diag, integer *m, integer *n, doublereal *a, integer *lda, 
	doublereal *work, ftnlen norm_len, ftnlen uplo_len, ftnlen diag_len)
{
    extern doublereal dlantr_(char *, char *, char *, integer *, integer *, 
	    doublereal *, integer *, doublereal *, ftnlen, ftnlen, ftnlen);

    *ret = dlantr_(norm, uplo, diag, m, n, a, lda, work, (ftnlen)1, (ftnlen)1,
	     (ftnlen)1);
    return 0;
} /* dlantrwrp_ */

/* Subroutine */ int dlapy2wrp_(doublereal *ret, doublereal *x, doublereal *y)
{
    extern doublereal dlapy2_(doublereal *, doublereal *);

    *ret = dlapy2_(x, y);
    return 0;
} /* dlapy2wrp_ */

/* Subroutine */ int dlapy3wrp_(doublereal *ret, doublereal *x, doublereal *y,
	 doublereal *z__)
{
    extern doublereal dlapy3_(doublereal *, doublereal *, doublereal *);

    *ret = dlapy3_(x, y, z__);
    return 0;
} /* dlapy3wrp_ */

/* Subroutine */ int dzsum1wrp_(doublereal *ret, integer *n, doublecomplex *
	cx, integer *incx)
{
    extern doublereal dzsum1_(integer *, doublecomplex *, integer *);

    /* Parameter adjustments */
    --cx;

    /* Function Body */
    *ret = dzsum1_(n, &cx[1], incx);
    return 0;
} /* dzsum1wrp_ */

/* Subroutine */ int icmax1wrp_(integer *ret, integer *n, complex *cx, 
	integer *incx)
{
    extern integer icmax1_(integer *, complex *, integer *);

    /* Parameter adjustments */
    --cx;

    /* Function Body */
    *ret = icmax1_(n, &cx[1], incx);
    return 0;
} /* icmax1wrp_ */

/* Subroutine */ int ieeeckwrp_(integer *ret, integer *ispec, real *zero, 
	real *one)
{
    extern integer ieeeck_(integer *, real *, real *);

    *ret = ieeeck_(ispec, zero, one);
    return 0;
} /* ieeeckwrp_ */

/* Subroutine */ int ilaclcwrp_(integer *ret, integer *m, integer *n, complex 
	*a, integer *lda)
{
    extern integer ilaclc_(integer *, integer *, complex *, integer *);

    *ret = ilaclc_(m, n, a, lda);
    return 0;
} /* ilaclcwrp_ */

/* Subroutine */ int ilaclrwrp_(integer *ret, integer *m, integer *n, complex 
	*a, integer *lda)
{
    extern integer ilaclr_(integer *, integer *, complex *, integer *);

    *ret = ilaclr_(m, n, a, lda);
    return 0;
} /* ilaclrwrp_ */

/* Subroutine */ int iladiagwrp_(integer *ret, char *diag, ftnlen diag_len)
{
    extern integer iladiag_(char *, ftnlen);

    *ret = iladiag_(diag, (ftnlen)1);
    return 0;
} /* iladiagwrp_ */

/* Subroutine */ int iladlcwrp_(integer *ret, integer *m, integer *n, 
	doublereal *a, integer *lda)
{
    extern integer iladlc_(integer *, integer *, doublereal *, integer *);

    *ret = iladlc_(m, n, a, lda);
    return 0;
} /* iladlcwrp_ */

/* Subroutine */ int iladlrwrp_(integer *ret, integer *m, integer *n, 
	doublereal *a, integer *lda)
{
    extern integer iladlr_(integer *, integer *, doublereal *, integer *);

    *ret = iladlr_(m, n, a, lda);
    return 0;
} /* iladlrwrp_ */

/* Subroutine */ int ilaprecwrp_(integer *ret, char *prec, ftnlen prec_len)
{
    extern integer ilaprec_(char *, ftnlen);

    *ret = ilaprec_(prec, (ftnlen)1);
    return 0;
} /* ilaprecwrp_ */

/* Subroutine */ int ilaslcwrp_(integer *ret, integer *m, integer *n, real *a,
	 integer *lda)
{
    extern integer ilaslc_(integer *, integer *, real *, integer *);

    *ret = ilaslc_(m, n, a, lda);
    return 0;
} /* ilaslcwrp_ */

/* Subroutine */ int ilaslrwrp_(integer *ret, integer *m, integer *n, real *a,
	 integer *lda)
{
    extern integer ilaslr_(integer *, integer *, real *, integer *);

    *ret = ilaslr_(m, n, a, lda);
    return 0;
} /* ilaslrwrp_ */

/* Subroutine */ int ilatranswrp_(integer *ret, char *trans, ftnlen trans_len)
{
    extern integer ilatrans_(char *, ftnlen);

    *ret = ilatrans_(trans, (ftnlen)1);
    return 0;
} /* ilatranswrp_ */

/* Subroutine */ int ilauplowrp_(integer *ret, char *uplo, ftnlen uplo_len)
{
    extern integer ilauplo_(char *, ftnlen);

    *ret = ilauplo_(uplo, (ftnlen)1);
    return 0;
} /* ilauplowrp_ */

/* Subroutine */ int ilazlcwrp_(integer *ret, integer *m, integer *n, 
	doublecomplex *a, integer *lda)
{
    extern integer ilazlc_(integer *, integer *, doublecomplex *, integer *);

    *ret = ilazlc_(m, n, a, lda);
    return 0;
} /* ilazlcwrp_ */

/* Subroutine */ int ilazlrwrp_(integer *ret, integer *m, integer *n, 
	doublecomplex *a, integer *lda)
{
    extern integer ilazlr_(integer *, integer *, doublecomplex *, integer *);

    *ret = ilazlr_(m, n, a, lda);
    return 0;
} /* ilazlrwrp_ */

/* Subroutine */ int izmax1wrp_(integer *ret, integer *n, doublecomplex *cx, 
	integer *incx)
{
    extern integer izmax1_(integer *, doublecomplex *, integer *);

    /* Parameter adjustments */
    --cx;

    /* Function Body */
    *ret = izmax1_(n, &cx[1], incx);
    return 0;
} /* izmax1wrp_ */

/* Subroutine */ int scsum1wrp_(real *ret, integer *n, complex *cx, integer *
	incx)
{
    extern doublereal scsum1_(integer *, complex *, integer *);

    /* Parameter adjustments */
    --cx;

    /* Function Body */
    *ret = scsum1_(n, &cx[1], incx);
    return 0;
} /* scsum1wrp_ */

/* Subroutine */ int slamchwrp_(real *ret, char *cmach, ftnlen cmach_len)
{
    extern doublereal slamch_(char *, ftnlen);

    *ret = slamch_(cmach, (ftnlen)1);
    return 0;
} /* slamchwrp_ */

/* Subroutine */ int slangbwrp_(real *ret, char *norm, integer *n, integer *
	kl, integer *ku, real *ab, integer *ldab, real *work, ftnlen norm_len)
{
    extern doublereal slangb_(char *, integer *, integer *, integer *, real *,
	     integer *, real *, ftnlen);

    *ret = slangb_(norm, n, kl, ku, ab, ldab, work, (ftnlen)1);
    return 0;
} /* slangbwrp_ */

/* Subroutine */ int slangewrp_(real *ret, char *norm, integer *m, integer *n,
	 real *a, integer *lda, real *work, ftnlen norm_len)
{
    extern doublereal slange_(char *, integer *, integer *, real *, integer *,
	     real *, ftnlen);

    *ret = slange_(norm, m, n, a, lda, work, (ftnlen)1);
    return 0;
} /* slangewrp_ */

/* Subroutine */ int slangtwrp_(real *ret, char *norm, integer *n, real *dl, 
	real *d__, real *du, ftnlen norm_len)
{
    extern doublereal slangt_(char *, integer *, real *, real *, real *, 
	    ftnlen);

    *ret = slangt_(norm, n, dl, d__, du, (ftnlen)1);
    return 0;
} /* slangtwrp_ */

/* Subroutine */ int slanhswrp_(real *ret, char *norm, integer *n, real *a, 
	integer *lda, real *work, ftnlen norm_len)
{
    extern doublereal slanhs_(char *, integer *, real *, integer *, real *, 
	    ftnlen);

    *ret = slanhs_(norm, n, a, lda, work, (ftnlen)1);
    return 0;
} /* slanhswrp_ */

/* Subroutine */ int slansbwrp_(real *ret, char *norm, char *uplo, integer *n,
	 integer *k, real *ab, integer *ldab, real *work, ftnlen norm_len, 
	ftnlen uplo_len)
{
    extern doublereal slansb_(char *, char *, integer *, integer *, real *, 
	    integer *, real *, ftnlen, ftnlen);

    *ret = slansb_(norm, uplo, n, k, ab, ldab, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* slansbwrp_ */

/* Subroutine */ int slansfwrp_(real *ret, char *norm, char *transr, char *
	uplo, integer *n, real *a, real *work, ftnlen norm_len, ftnlen 
	transr_len, ftnlen uplo_len)
{
    extern doublereal slansf_(char *, char *, char *, integer *, real *, real 
	    *, ftnlen, ftnlen, ftnlen);

    /* Parameter adjustments */
    --a;

    /* Function Body */
    *ret = slansf_(norm, transr, uplo, n, &a[1], work, (ftnlen)1, (ftnlen)1, (
	    ftnlen)1);
    return 0;
} /* slansfwrp_ */

/* Subroutine */ int slanspwrp_(real *ret, char *norm, char *uplo, integer *n,
	 real *ap, real *work, ftnlen norm_len, ftnlen uplo_len)
{
    extern doublereal slansp_(char *, char *, integer *, real *, real *, 
	    ftnlen, ftnlen);

    *ret = slansp_(norm, uplo, n, ap, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* slanspwrp_ */

/* Subroutine */ int slanstwrp_(real *ret, char *norm, integer *n, real *d__, 
	real *e, ftnlen norm_len)
{
    extern doublereal slanst_(char *, integer *, real *, real *, ftnlen);

    *ret = slanst_(norm, n, d__, e, (ftnlen)1);
    return 0;
} /* slanstwrp_ */

/* Subroutine */ int slansywrp_(real *ret, char *norm, char *uplo, integer *n,
	 real *a, integer *lda, real *work, ftnlen norm_len, ftnlen uplo_len)
{
    extern doublereal slansy_(char *, char *, integer *, real *, integer *, 
	    real *, ftnlen, ftnlen);

    *ret = slansy_(norm, uplo, n, a, lda, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* slansywrp_ */

/* Subroutine */ int slantbwrp_(real *ret, char *norm, char *uplo, char *diag,
	 integer *n, integer *k, real *ab, integer *ldab, real *work, ftnlen 
	norm_len, ftnlen uplo_len, ftnlen diag_len)
{
    extern doublereal slantb_(char *, char *, char *, integer *, integer *, 
	    real *, integer *, real *, ftnlen, ftnlen, ftnlen);

    *ret = slantb_(norm, uplo, diag, n, k, ab, ldab, work, (ftnlen)1, (ftnlen)
	    1, (ftnlen)1);
    return 0;
} /* slantbwrp_ */

/* Subroutine */ int slantpwrp_(real *ret, char *norm, char *uplo, char *diag,
	 integer *n, real *ap, real *work, ftnlen norm_len, ftnlen uplo_len, 
	ftnlen diag_len)
{
    extern doublereal slantp_(char *, char *, char *, integer *, real *, real 
	    *, ftnlen, ftnlen, ftnlen);

    *ret = slantp_(norm, uplo, diag, n, ap, work, (ftnlen)1, (ftnlen)1, (
	    ftnlen)1);
    return 0;
} /* slantpwrp_ */

/* Subroutine */ int slantrwrp_(real *ret, char *norm, char *uplo, char *diag,
	 integer *m, integer *n, real *a, integer *lda, real *work, ftnlen 
	norm_len, ftnlen uplo_len, ftnlen diag_len)
{
    extern doublereal slantr_(char *, char *, char *, integer *, integer *, 
	    real *, integer *, real *, ftnlen, ftnlen, ftnlen);

    *ret = slantr_(norm, uplo, diag, m, n, a, lda, work, (ftnlen)1, (ftnlen)1,
	     (ftnlen)1);
    return 0;
} /* slantrwrp_ */

/* Subroutine */ int slapy2wrp_(real *ret, real *x, real *y)
{
    extern doublereal slapy2_(real *, real *);

    *ret = slapy2_(x, y);
    return 0;
} /* slapy2wrp_ */

/* Subroutine */ int slapy3wrp_(real *ret, real *x, real *y, real *z__)
{
    extern doublereal slapy3_(real *, real *, real *);

    *ret = slapy3_(x, y, z__);
    return 0;
} /* slapy3wrp_ */

/* Subroutine */ int zladivwrp_(doublecomplex *ret, doublecomplex *x, 
	doublecomplex *y)
{
    /* System generated locals */
    doublecomplex z__1;

    /* Local variables */
    extern /* Double Complex */ VOID wzladiv_(doublecomplex *, doublecomplex *
	    , doublecomplex *);

    wzladiv_(&z__1, x, y);
    ret->r = z__1.r, ret->i = z__1.i;
    return 0;
} /* zladivwrp_ */

/* Subroutine */ int zlangbwrp_(doublereal *ret, char *norm, integer *n, 
	integer *kl, integer *ku, doublecomplex *ab, integer *ldab, 
	doublereal *work, ftnlen norm_len)
{
    extern doublereal zlangb_(char *, integer *, integer *, integer *, 
	    doublecomplex *, integer *, doublereal *, ftnlen);

    *ret = zlangb_(norm, n, kl, ku, ab, ldab, work, (ftnlen)1);
    return 0;
} /* zlangbwrp_ */

/* Subroutine */ int zlangewrp_(doublereal *ret, char *norm, integer *m, 
	integer *n, doublecomplex *a, integer *lda, doublereal *work, ftnlen 
	norm_len)
{
    extern doublereal zlange_(char *, integer *, integer *, doublecomplex *, 
	    integer *, doublereal *, ftnlen);

    *ret = zlange_(norm, m, n, a, lda, work, (ftnlen)1);
    return 0;
} /* zlangewrp_ */

/* Subroutine */ int zlangtwrp_(doublereal *ret, char *norm, integer *n, 
	doublecomplex *dl, doublecomplex *d__, doublecomplex *du, ftnlen 
	norm_len)
{
    extern doublereal zlangt_(char *, integer *, doublecomplex *, 
	    doublecomplex *, doublecomplex *, ftnlen);

    *ret = zlangt_(norm, n, dl, d__, du, (ftnlen)1);
    return 0;
} /* zlangtwrp_ */

/* Subroutine */ int zlanhbwrp_(doublereal *ret, char *norm, char *uplo, 
	integer *n, integer *k, doublecomplex *ab, integer *ldab, doublereal *
	work, ftnlen norm_len, ftnlen uplo_len)
{
    extern doublereal zlanhb_(char *, char *, integer *, integer *, 
	    doublecomplex *, integer *, doublereal *, ftnlen, ftnlen);

    *ret = zlanhb_(norm, uplo, n, k, ab, ldab, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* zlanhbwrp_ */

/* Subroutine */ int zlanhewrp_(doublereal *ret, char *norm, char *uplo, 
	integer *n, doublecomplex *a, integer *lda, doublereal *work, ftnlen 
	norm_len, ftnlen uplo_len)
{
    extern doublereal zlanhe_(char *, char *, integer *, doublecomplex *, 
	    integer *, doublereal *, ftnlen, ftnlen);

    *ret = zlanhe_(norm, uplo, n, a, lda, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* zlanhewrp_ */

/* Subroutine */ int zlanhfwrp_(doublereal *ret, char *norm, char *transr, 
	char *uplo, integer *n, doublecomplex *a, doublereal *work, ftnlen 
	norm_len, ftnlen transr_len, ftnlen uplo_len)
{
    extern doublereal zlanhf_(char *, char *, char *, integer *, 
	    doublecomplex *, doublereal *, ftnlen, ftnlen, ftnlen);

    /* Parameter adjustments */
    --a;

    /* Function Body */
    *ret = zlanhf_(norm, transr, uplo, n, &a[1], work, (ftnlen)1, (ftnlen)1, (
	    ftnlen)1);
    return 0;
} /* zlanhfwrp_ */

/* Subroutine */ int zlanhpwrp_(doublereal *ret, char *norm, char *uplo, 
	integer *n, doublecomplex *ap, doublereal *work, ftnlen norm_len, 
	ftnlen uplo_len)
{
    extern doublereal zlanhp_(char *, char *, integer *, doublecomplex *, 
	    doublereal *, ftnlen, ftnlen);

    *ret = zlanhp_(norm, uplo, n, ap, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* zlanhpwrp_ */

/* Subroutine */ int zlanhswrp_(doublereal *ret, char *norm, integer *n, 
	doublecomplex *a, integer *lda, doublereal *work, ftnlen norm_len)
{
    extern doublereal zlanhs_(char *, integer *, doublecomplex *, integer *, 
	    doublereal *, ftnlen);

    *ret = zlanhs_(norm, n, a, lda, work, (ftnlen)1);
    return 0;
} /* zlanhswrp_ */

/* Subroutine */ int zlanhtwrp_(doublereal *ret, char *norm, integer *n, 
	doublereal *d__, doublecomplex *e, ftnlen norm_len)
{
    extern doublereal zlanht_(char *, integer *, doublereal *, doublecomplex *
	    , ftnlen);

    *ret = zlanht_(norm, n, d__, e, (ftnlen)1);
    return 0;
} /* zlanhtwrp_ */

/* Subroutine */ int zlansbwrp_(doublereal *ret, char *norm, char *uplo, 
	integer *n, integer *k, doublecomplex *ab, integer *ldab, doublereal *
	work, ftnlen norm_len, ftnlen uplo_len)
{
    extern doublereal zlansb_(char *, char *, integer *, integer *, 
	    doublecomplex *, integer *, doublereal *, ftnlen, ftnlen);

    *ret = zlansb_(norm, uplo, n, k, ab, ldab, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* zlansbwrp_ */

/* Subroutine */ int zlanspwrp_(doublereal *ret, char *norm, char *uplo, 
	integer *n, doublecomplex *ap, doublereal *work, ftnlen norm_len, 
	ftnlen uplo_len)
{
    extern doublereal zlansp_(char *, char *, integer *, doublecomplex *, 
	    doublereal *, ftnlen, ftnlen);

    *ret = zlansp_(norm, uplo, n, ap, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* zlanspwrp_ */

/* Subroutine */ int zlansywrp_(doublereal *ret, char *norm, char *uplo, 
	integer *n, doublecomplex *a, integer *lda, doublereal *work, ftnlen 
	norm_len, ftnlen uplo_len)
{
    extern doublereal zlansy_(char *, char *, integer *, doublecomplex *, 
	    integer *, doublereal *, ftnlen, ftnlen);

    *ret = zlansy_(norm, uplo, n, a, lda, work, (ftnlen)1, (ftnlen)1);
    return 0;
} /* zlansywrp_ */

/* Subroutine */ int zlantbwrp_(doublereal *ret, char *norm, char *uplo, char 
	*diag, integer *n, integer *k, doublecomplex *ab, integer *ldab, 
	doublereal *work, ftnlen norm_len, ftnlen uplo_len, ftnlen diag_len)
{
    extern doublereal zlantb_(char *, char *, char *, integer *, integer *, 
	    doublecomplex *, integer *, doublereal *, ftnlen, ftnlen, ftnlen);

    *ret = zlantb_(norm, uplo, diag, n, k, ab, ldab, work, (ftnlen)1, (ftnlen)
	    1, (ftnlen)1);
    return 0;
} /* zlantbwrp_ */

/* Subroutine */ int zlantpwrp_(doublereal *ret, char *norm, char *uplo, char 
	*diag, integer *n, doublecomplex *ap, doublereal *work, ftnlen 
	norm_len, ftnlen uplo_len, ftnlen diag_len)
{
    extern doublereal zlantp_(char *, char *, char *, integer *, 
	    doublecomplex *, doublereal *, ftnlen, ftnlen, ftnlen);

    *ret = zlantp_(norm, uplo, diag, n, ap, work, (ftnlen)1, (ftnlen)1, (
	    ftnlen)1);
    return 0;
} /* zlantpwrp_ */

/* Subroutine */ int zlantrwrp_(doublereal *ret, char *norm, char *uplo, char 
	*diag, integer *m, integer *n, doublecomplex *a, integer *lda, 
	doublereal *work, ftnlen norm_len, ftnlen uplo_len, ftnlen diag_len)
{
    extern doublereal zlantr_(char *, char *, char *, integer *, integer *, 
	    doublecomplex *, integer *, doublereal *, ftnlen, ftnlen, ftnlen);

    *ret = zlantr_(norm, uplo, diag, m, n, a, lda, work, (ftnlen)1, (ftnlen)1,
	     (ftnlen)1);
    return 0;
} /* zlantrwrp_ */

